name: API Tests with Newman

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-newman-tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Newman
        run: npm install -g newman

      - name: Run API Tests
        run: newman run postman/collection.json -e postman/environment.json -r cli,html --reporter-html-export results/report.html

      - name: Upload Newman Report
        uses: actions/upload-artifact@v3
        with:
          name: newman-report
          path: results/report.html
