# This is a basic workflow to help you get started with Actions

name: API Collection Run with Newman CI
# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Create dir
        run: |
         mkdir artifact

      # Runs a single command using the runners shell
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
           node-version: '16'

     
    # Newman installation globally
      - name: install Newman
        run: |
         npm install -g newman
         npm install -g newman-reporter-htmlextra

    # Run the POSTMAN collection 
      - name: Run POSTMAN collection with html report
        run: newman run "API Challenges.postman_collection.json" -r cli,htmlextra --reporter-htmlextra-export artifact/htmlreport.html

    # Upload the reports to TestArtifacts directory
      - name: Output the Result
        uses: actions/upload-artifact@v4
        with:
         name: Reports
         path: artifact
